name: MIT_API
version: 1.0.0
description: >-
  Rest API For student project
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  prompts: ^1.3.1
  http: ^0.12.0+2
  crypto: ^2.1.5
  convert: ^2.1.1
  jaguar_jwt: ^2.1.6
  yaml: ^2.2.1