POST http://localhost:8080/student
Authorization: Bearer <token>
content-type: application/json

{
    "firstname": "Firstname",
    "lastname": "Lastname",
    "email": "Email",
    "password": "Password"
}
