POST http://localhost:8080/student
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikd1aWxsYXVtZSBRdWl0dGV0IiwiZW1haWwiOiJndWlsbGF1bWUucXVpdHRldEBnbWFpbC5jb20iLCJpYXQiOjE1MTYyMzkwMjJ9.n8tWHvSIN_wTNYiMn-wVyf_iYFkIWmgJzZ12_ylVOoA
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikd1aWxsYXVtZSBRdWl0dGV0IiwiZW1haWwiOiJndWlsbGF1bWUucXVpdHRldEBnbWFpbC5jb20iLCJpYXQiOjE1MTYyMzkwMjJ9.5jhqKZVxcjKFIzs4DOj6FcwREG58NOS1RFA90QKWMck
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkphbWJvbi1Gcm9tYWdlIExlcmF0IiwiZW1haWwiOiJqZWFuLXNlYmFzdGllbi5sZXJhdEBoZWguYmUiLCJpYXQiOjE1MTYyMzkwMjJ9.PA3D6G7BTarXHz0VdNS6zSCmSigA_yw--KWRvQIbBSI
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkphbWJvbi1Gcm9tYWdlIExlcmF0IiwiZW1haWwiOiJqZWFuLXNlYmFzdGllbi5sZXJhdEBoZWguYmUiLCJpYXQiOjE1MTYyMzkwMjJ9.NdNPWCUaMUwUmFceXxEkFXAl-oyWKV569erJ93OqIqs
content-type: application/json

{
    "firstname": "Valentin",
    "lastname": "Denis",
    "email": "valentin.denis@std.heh.be",
    "password": "Test123*"
}
