GET http://localhost:8080/teacher?email=jean-sebastien.lerat@heh.be
Authorization: Bearer <token>


PUT http://localhost:8080/teacher
content-type: application/json
Authorization: Bearer <token>

{
    "firstname": "Firstname",
    "lastname": "lastname",
    "email": "mail"
}


