# credentials:
#  nom: 'Denis'
#  prenom: 'Valentin'
#  email: "valentin.denis@std.heh.be"

credentials:
 nom: 'Hubert'
 prenom: 'Fabrice'
 email: "fabrice.hubert@heh.be"

PathToCompile:
  path: 'D:\Valentin\Bureau\compiler\main.asm'