GET http://localhost:8080/compile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbC5kZW5pc0BoZWguYmUiLCJuYW1lIjoiRGVuaXMgVmFsIiwiZXhwIjoxNjA5MzQzODYzLCJpYXQiOjE2MDkzNDAyNjN9.CImcWWnSaSuXh06tSTsKioOUzoB_5EGcZ7r3Cfk8Uvw
