POST http://localhost:8080/gcc
Authorization: Bearer <token>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.ccc"
Content-Type: text/plain

< ./test.c
------WebKitFormBoundary7MA4YWxkTrZu0gW--
